\connect sales

    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        email text NOT NULL,
        password text NOT NULL,
        role text NOT NULL DEFAULT 'seller',
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    
    Insert into users(id, name, email, password, role) values( 1, 'Edson A. do Nascimento', 'pele@magazineaziul.com.br','123mudar', 'NationalDirector');
    Insert into users(id, name, email, password, role) values( 2, 'Vagner Mancini', 'vagner.mancini@magazineaziul.com.br','123mudar', 'Director');
    Insert into users(id, name, email, password, role) values( 3, 'Abel Ferreira', 'abel.ferreira@magazineaziul.com.br','123mudar', 'Director');
    Insert into users(id, name, email, password, role) values( 4, 'Rogerio Ceni', 'rogerio.ceni@magazineaziul.com.br','123mudar', 'Director');
    Insert into users(id, name, email, password, role) values( 5, 'Ronaldinho Gaucho', 'ronaldinho.gaucho@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 6, 'Roberto Firmino', 'roberto.firmino@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 7, 'Alex de Souza', 'alex.de.souza@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 8, 'Françoaldo Souza', 'françoaldo.souza@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 9, 'Romário Faria', 'romário.faria@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 10, 'Ricardo Goulart', 'ricardo.goulart@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 11, 'Dejan Petkovic', 'dejan.petkovic@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 12, 'Deyverson Acosta', 'deyverson.acosta@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 13, 'Harlei Silva', 'harlei.silva@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 14, 'Walter Henrique', 'walter.henrique@magazineaziul.com.br','123mudar', 'Manager');
    Insert into users(id, name, email, password, role) values( 15,'Afonso Afancar','afonso.afancar@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 16,'Alceu Andreoli','alceu.andreoli@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 17,'Amalia Zago','amalia.zago@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 18,'Carlos Eduardo','carlos.eduardo@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 19,'Luiz Felipe','luiz.felipe@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 20,'Breno','breno@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 21,'Emanuel','emanuel@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 22,'Ryan','ryan@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 23,'Vitor Hugo','vitor.hugo@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 24,'Yuri','yuri@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 25,'Benjamin','benjamin@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 26,'Erick','erick@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 27,'Enzo Gabriel','enzo.gabriel@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 28,'Fernando','fernando@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 29,'Joaquim','joaquim@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 30,'André','andré@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 31,'Raul','raul@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 32,'Marcelo','marcelo@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 33,'Julio César','julio.césar@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 34,'Cauê','cauê@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 35,'Benício','benício@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 36,'Vitor Gabriel','vitor.gabriel@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 37,'Augusto','augusto@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 38,'Pedro Lucas','pedro.lucas@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 39,'Luiz Gustavo','luiz.gustavo@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 40,'Giovanni','giovanni@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 41,'Renato','renato@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 42,'Diego','diego@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 43,'João Paulo','joão.paulo@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 44,'Renan','renan@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 45,'Luiz Fernando','luiz.fernando@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 46,'Anthony','anthony@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 47,'Lucas Gabriel','lucas.gabriel@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 48,'Thales','thales@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 49,'Luiz Miguel','luiz.miguel@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 50,'Henry','henry@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 51,'Marcos Vinicius','marcos.vinicius@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 52,'Kevin','kevin@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 53,'Levi','levi@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 54,'Enrico','enrico@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 55,'João Lucas','joão.lucas@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 56,'Hugo','hugo@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 57,'Luiz Guilherme','luiz.guilherme@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 58,'Matheus Henrique','matheus.henrique@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 59,'Miguel','miguel@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 60,'Davi','davi@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 61,'Gabriel','gabriel@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 62,'Arthur','arthur@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 63,'Lucas','lucas@magazineaziul.com.br','123mudar', 'Seller');
    Insert into users(id, name, email, password, role) values( 64,'Matheus','matheus@magazineaziul.com.br','123mudar', 'Seller');