\connect sales
	CREATE TABLE boards (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        "DirectorID" integer NOT NULL,
        CONSTRAINT "PK_boards" PRIMARY KEY (id)
    );
    Insert into boards(id, name, "DirectorID") values( 1, 'Sul', 2);
    Insert into boards(id, name, "DirectorID") values( 2, 'Sudeste', 3);
    Insert into boards(id, name, "DirectorID") values( 3, 'Centro-oeste', 4);