\connect sales
	CREATE TABLE units (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        latitude text NOT NULL,
        longitude text NOT NULL,
        "ManagerID" integer NOT NULL,
        "BoardID" integer NOT NULL,
        CONSTRAINT "PK_units" PRIMARY KEY (id)
    );
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 1, 'Porto Alegre', '-30.048750057541955', '-51.228587422990806', 5, 1);
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 2, 'Florianopolis', '-27.55393525017396', '-48.49841515885026', 6, 1);
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 3, 'Curitiba', '-25.473704465731746', '-49.24787198992874', 7, 1);
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 4, 'Sao Paulo', '-23.544259437612844', '-46.64370714029131', 8, 2);
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 5, 'Rio de Janeiro', '-22.923447510604802', '-43.23208495438858', 9, 2);
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 6, 'Belo Horizonte', '-19.917854829716372', '-43.94089385954766', 10, 2);
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 7, 'Vitória', '-20.340992420772206', '-40.38332271475097', 11, 2);
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 8, 'Campo Grande', '-20.462652006300377', '-54.615658937666645', 12, 3);
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 9, 'Goiania', '-16.673126240814387', '-49.25248826354209', 13, 3);
    Insert into units(id, name, latitude, longitude, "ManagerID", "BoardID") values( 10, 'Cuiaba', '-15.601754458320842', '-56.09832706558089', 14, 3);