\connect sales
	CREATE TABLE sales (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        created_at timestamp with time zone NOT NULL,
        roaming_unity_id integer NULL,
        "SellerID" integer NOT NULL,
        "UnityID" integer NOT NULL,
        CONSTRAINT "PK_sales" PRIMARY KEY (id)
    );    