\connect sales
	CREATE TABLE sales (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        value real NULL,
        latitude text NOT NULL,
        longitude text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        roaming_unit_id integer NULL,
        "SellerID" integer NOT NULL,
        "UnitID" integer NOT NULL,
        CONSTRAINT "PK_sales" PRIMARY KEY (id)
    );    