\connect sales

CREATE TABLE users (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "username" text NOT NULL,
    "password" text NOT NULL,
    "role" text NOT NULL DEFAULT 'employee',
    CONSTRAINT "PK_users" PRIMARY KEY ("id")
);

Insert into users(id, username, password, role) values( 1, 'Admin', '12345', 'manager');